### PR TITLE
Update class.cpp to make code compatible with MSVC

### PR DESCRIPTION
**Pull request by andriish**
Update class.cpp to make code compatible with MSVC.

Should solve #298

### CODE REVIEW

**Review by lyskov — CHANGES_REQUESTED** [review]
Hm... @andriish i do not think this code is doing what you intended (see https://en.cppreference.com/w/cpp/string/basic_string/rfind). Please instead call  `begins_with` from https://github.com/RosettaCommons/binder/blob/master/source/util.cpp#L88C6-L88C17
Thanks,

**Comment by andriish** [comment]
Hi @lyskov,
the code does what is expected:
```
$ root -l
root [0] std::string return_type="class XXX"
(std::string &) "class XXX"
root [1] if (return_type.rfind("class ", 0) == 0) return_type = return_type.substr(6);
root [2] return_type
(std::string &) "XXX"
root [3] 
```
I havent seen your `begins_with`, will use it.
But I would actually update `begins_with`.

Andrii

**Comment by andriish** [comment]
@lyskov

**Comment by lyskov** [comment]
> ```
> $ root -l
> root [0] std::string return_type="class XXX"
> (std::string &) "class XXX"
> root [1] if (return_type.rfind("class ", 0) == 0) return_type = return_type.substr(6);
> root [2] return_type
> (std::string &) "XXX"
> root [3] 
> ```
-- oh, i see, so the `pos` argument is offset from the _beginning of the string_ and not the end 🤦🏻‍♂️, - yeah, that will work too!
Btw, do you use some kind of interpreter to test this, which one? 

> I havent seen your `begins_with`, will use it. But I would actually update `begins_with`.
-- could you please elaborate? Ie do you expect `rfind` implementation to be more efficient or something? 
Thanks,

**Review by lyskov — APPROVED** [review]
LGTM, - thank you @andriish !

**Comment by lyskov** [comment]
> I havent seen your begins_with, will use it. But I would actually update begins_with.

@andriish could it be that you are referring to the old study that claims that for natural languages it yield better performance to always search from the end of the strings and not beginning (ie there is less number of strings that ends the same compare to number of strings that have begin with same sequence)?

**Comment by andriish** [comment]
-- The interpreter is https://root.cern/
 -- The  "rfind" is  just "oneliner for string::starts_with" implemented in C++11

**Pull request merged**
