### PR TITLE
Update class.cpp to avoid else after return

### PR DESCRIPTION
**Pull request by andriish**
Update class.cpp to avoid else after return

### CODE REVIEW

**Comment by andriish** [comment]
Also contains https://github.com/RosettaCommons/binder/pull/296

**Comment by andriish** [comment]
The rule  clang complaining about is here: 

https://clang.llvm.org/extra/clang-tidy/checks/readability/else-after-return.html

This in in the *generated* code.

**Comment by andriish** [comment]
@lyskov

**Review by lyskov — APPROVED** [review]
LGTM, - thank you @andriish !

**Pull request merged**
