### PR TITLE
Update context.cpp to avoid else after return

### PR DESCRIPTION
**Pull request by andriish**
Update context.cpp to avoid else after return

### CODE REVIEW

**Comment by andriish** [comment]
Also contains https://github.com/RosettaCommons/binder/pull/296

**Review by lyskov — COMMENTED** [review]
Hm... i do like the explicit `else` in https://github.com/RosettaCommons/binder/pull/292/files#diff-a991df2f19ad54fba2d1e4aa256a303fb097f489381a1adf8c5319726132c651L113 and i believe other changes now merged?

**Comment by andriish** [comment]
The rule is here:

https://clang.llvm.org/extra/clang-tidy/checks/readability/else-after-return.html

But for the automatically generated code it also makes sense to reduce the size.

**Comment by lyskov** [comment]
Oh, i have not realized that this is inside generated code, - i see your point, - makes sense to me!

**Review by lyskov — APPROVED** [review]
LGTM, - thank you @andriish !

**Pull request merged**
