### PR TITLE
Try to fix the test

### LINKED ISSUE #231: Unstable `make -j`.
I've noticed that if I `make -j` binder when `cmake` was run with tests enabled, it might sometimes fail with
```
#22 7.131 make[2]: Leaving directory '/build'
#22 7.138 [ 18%] Built target binder
#22 7.140 make[1]: Leaving directory '/build'
#22 7.141 make: *** [Makefile:144: all] Error 2
#22 ERROR: executor failed running [/bin/sh -c make "-j$(nproc)"]: exit code: 2
```

I ran it with `binder` checked out from the current _master_ branch, specifically this commit:  https://github.com/RosettaCommons/binder/commit/7ac60d98ac95ab2d2b47bb46212f54d55f8face0 I have not debugged this or checked other commits. I would recommend using `git bisect` to isolate where the issue came from.

Here is the dockerfile I used:
```docker
FROM ubuntu:20.04 as base

# Config
ARG BRANCH="master"
ARG CLANG_VERSION=14

# General dependencies
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
 && apt-get install -yq wget gnupg \
 && rm -rf /var/lib/apt/lists/*

# Add llvm repo
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${CLANG_VERSION} main" >> /etc/apt/sources.list

# Run dependencies
RUN apt-get update \
 && apt-get install -yq "clang-${CLANG_VERSION}" \
 && rm -rf /var/lib/apt/lists/*

FROM base as build

# Build dependencies
RUN apt-get update
RUN apt-get install -yq \
	"libclang-${CLANG_VERSION}-dev" \
	cmake \
	git

# pybind11
RUN git clone https://github.com/pybind/pybind11 /pybind11
RUN apt-get install -yq python3-pip python3-dev
RUN pip3 install pytest
WORKDIR "/py-build"
RUN cmake \
	-DCMAKE_CXX_COMPILER="$(which clang++-"${CLANG_VERSION}")" \
	/pybind11
RUN make "-j$(nproc)"
RUN make install

# Clone binder source
ARG REPO="https://github.com/RosettaCommons/binder.git"
COPY ./binder /binder

# Binder
WORKDIR "/build"
RUN cmake \
	-DCMAKE_CXX_COMPILER="$(which clang++-"${CLANG_VERSION}")" \
	-DBINDER_ENABLE_TEST=ON \
	/binder
RUN make "-j$(nproc)"
```

### LINKED ISSUE #239: Official docker image
Would you be open to a PR that auto-publishes a docker build of this to with the image tag `gchr.io/RosettaCommons/binder` on updates to master?

Right now I'm manually maintaining `zwimer/binder`; though I rebuilt this every time master is updated.

What I could do is add a github workflows YML to automatically do this. Pushing to `gchr.io/RosettaCommons/binder` is easy as that is github's docker repo. Though, I could easily make this work for a dockerhub ID (ie just the tag `RosettaCommons/binder`) if you wanted to add 2 github secrets, `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`; these would be protected by the github secrets mechanisms.

Here is an example `yml` file I could make the PR using (though I would slightly modify it): https://github.com/zwimer/caddy-cloudflare/blob/master/.github/workflows/publish.yml

### PR DESCRIPTION
**Pull request by andriish**
Add `binder` as a dependency for the tests.

Should fix #231

Tag @zwimer 
Edit: correct the issue number

### CODE REVIEW

**Comment by zwimer** [comment]
Did you mean: https://github.com/RosettaCommons/binder/issues/231 ?

**Comment by zwimer** [comment]
@andriish I can no longer reproduce the build failure with this change, which is good.

**Comment by andriish** [comment]
Hi @zwimer , yes, #231.

**Review by lyskov — APPROVED** [review]
LGTM!

**Comment by lyskov** [comment]
Looks like this fallen-off from my radar, - thank you for fixing this @andriish !

**Pull request merged**
