### PR TITLE
fix division binding issue

### PR DESCRIPTION
**Pull request by zwimer**
Fixes https://github.com/RosettaCommons/binder/issues/232

### CODE REVIEW

**Comment by zwimer** [comment]
I chose to switch to true division, instead of floor division, mostly because the signs are the same. I.e. python does `3 // 2` for floor division and `3 / 2` for true division. Since these are for use defined classes we could
1. Do truediv (I did this)
2. Do floordiv
3. Do both

**Comment by lyskov** [comment]
Thank you for PR @zwimer ! Unfortunately i saw this only after i pushed my fix to master so i will just close this. (all these changes now in master)

**Comment by zwimer** [comment]
@lyskov This also fixes `__itruediv__` for `/=`.

**Comment by zwimer** [comment]
Oh, I see they are both updated in master now!

**Pull request closed without merging**
