### PR TITLE
Binder limitations documentation added

### PR DESCRIPTION
**Pull request by zwimer**
This PR adds documentation about some of binder's limitations. Right now, it is focussed mostly on operatos.

I am not sure how to generate the docs from my file, though I verified the `limitations.rst` is as I desire via `rst2pdf`.

### CODE REVIEW

**Comment by zwimer** [comment]
Related:
https://github.com/RosettaCommons/binder/issues/220
https://github.com/RosettaCommons/binder/issues/225
https://github.com/RosettaCommons/binder/issues/226
https://github.com/RosettaCommons/binder/issues/227
https://github.com/RosettaCommons/binder/issues/228

**Review by lyskov — COMMENTED** [review]
Looks good to me! Could you please update it so it reflect recent merges? Thanks,

**Comment by zwimer** [comment]
I did with the most recent commits! Though, if you plan to merge https://github.com/RosettaCommons/binder/pull/237 then I would hold off on merging this, as it will require an update for that PR as well- or we could update the docs this PR creates in that PR instead if preferred.

**Comment by lyskov** [comment]
Thank you @zwimer ! I think lets merge this now and when/if #237 is merged then it related doc update could be included in it.

**Review by lyskov — APPROVED** [review]
LGTM, - thank you for putting this together @zwimer !

**Pull request merged**
